<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerALN0lnP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerALN0lnP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerALN0lnP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerALN0lnP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerALN0lnP\App_KernelDevDebugContainer([
    'container.build_hash' => 'ALN0lnP',
    'container.build_id' => '97144ae8',
    'container.build_time' => 1578255592,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerALN0lnP');
